model_name: "HuggingFaceTB/SmolLM2-135M"
batch_size: 64
max_length: 512
lr: 0.0001
num_warmup_steps: 100
num_decay_steps: 200
deq_max_steps: 0
phantom_steps: 1
trainer_args:
  max_steps: 32000
  precision: bf16-true
  gradient_clip_val: 2.0
  # devices: 2
  # strategy: "deepspeed_stage_2"
