datasets:
  - weight: 1.0
    args:
      path: "Zyphra/dclm-dedup"
      split: train
      streaming: True
model_name: "HuggingFaceTB/SmolLM2-135M"
batch_size: 128
max_length: 512
lr: 0.001
num_warmup_steps: 100
num_decay_steps: 200
deq_max_steps: 0
phantom_steps: 0
distance_loss_weight: 0.8
trainer_args:
  max_steps: 2000
  precision: bf16-true
  gradient_clip_val: 2.0
  accumulate_grad_batches: 1
  # devices: 2
  # strategy: "deepspeed_stage_1"
